@endpoint = http://localhost:3000/api/v1/cars


###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "make":"Mini",
    "model":"Cooper",
    "year": 1950
}


###
@newCar = {{postACar.response.body._id}}

###
GET {{endpoint}} HTTP/1.1
content-type : application/json
x-api-key: blahblah

###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json
x-api-key: blahblah


//###
//GET  {{endpoint}}/:id HTTP/3.0
//content-type: application/json
//x-api-key: blahblah

//{
   // "id": "6ab5433b731233603477082e"
//}




###

DELETE  {{endpoint}}/:id HTTP/1.1
content-type: application/json

{
    "_id":"6ac602d862ecd6a5c914c545"
}



###

PUT  {{endpoint}}/:id HTTP/3.0
content-type: application/json
  
{   
    "id" : "6abcd535d02134a4c5c54f7b",   
    "model":"Copper",
     "make":"Mini", 
     "year" : 1980
}
  
