@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar

###
POST {{endpoint}} HTTP/1.1
content-type: application/json

   {
    "make":"Mini",
    "model":"Copper"
   }

###
@newCar = {{postACar.response.body._id}}

###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json


###

DELETE  {{endpoint}}/:id HTTP/1.1
content-type: application/json

{
    "_id":"6abcc3de09e8ab3a52192a23"
}



###

PUT  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json
  
{      
    "model":"Copper",
     "make":"Mini"
}
  
