@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar

###
POST {{endpoint}} HTTP/1.1
content-type: application/json

   {
    "make":"Mini",
    "model":"Cooper",
    "year": 1950
   }

###
@newCar = {{postACar.response.body._id}}

###
GET {{endpoint}} HTTP/1.1
content-type : application/json
x-api-key: blahblah

###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json


###

DELETE  {{endpoint}}/:id HTTP/1.1
content-type: application/json

{
    "_id":"6abccfecba01a6609d1a7d5d"
}



###

PUT  {{endpoint}}/:id HTTP/3.0
content-type: application/json
  
{   
    "id" : "6abcd535d02134a4c5c54f7b",   
    "model":"Copper",
     "make":"Mini", 
     "year" : 1980
}
  
